services:
    tabby:
        build: .
        restart: always
        depends_on:
        - db
        environment:
        - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db/${MARIADB_DATABASE}
        - PORT=80
        - DEBUG=False
        - DOCKERIZE_ARGS="-wait tcp://db:3306 -timeout 60s"
        # - APP_DIST_STORAGE="file:///app-dist"

    db:
        image: mariadb:10.7.1
        restart: always
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
